language: ruby
rvm:
  - 1.9.3
  - 2.0.0

gemfile:
  - Gemfile

env:
- DB=mysql

before_script:
 - mysql -e 'create database frustration_test;'

script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate:reset
  - bundle exec rake db:test:prepare
  - bundle exec rspec spec/

notifications:
  irc:
    on_success: change
    on_failure: always
    channels:
      - "irc.freenode.org#frustrationme"
